/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misVentanas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import misClases.Mozo;
import misClases.Pedido;
import misClasesCola.ArrayCola;
import misClasesLista.ListaLEG;
import misClasesLista.NodoLEG;

/**
 *
 * @author Joshephpm
 */
public class miListaPedido extends javax.swing.JPanel {

    /**
     * Creates new form miListaPedido
     */
    DefaultTableModel modelo;
    ListaLEG<Mozo> listM;
    public miListaPedido() {
        initComponents();
        String []titulo={"Mozo","Año Expe","CantidadPlatos","MontoRecaudado"};
        modelo= new DefaultTableModel(null,titulo);
        jTableVisualizar.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldAño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonTabla2 = new javax.swing.JButton();
        jButtonTabla1 = new javax.swing.JButton();
        jTextFieldMonto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisualizar = new javax.swing.JTable();
        jButtonRegresar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 420));

        jPanel1.setBackground(new java.awt.Color(61, 55, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 420));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Año de experiencia:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monto:");

        jButtonTabla2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTabla2.setText("Visualizar tabla 1");
        jButtonTabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabla2ActionPerformed(evt);
            }
        });

        jButtonTabla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTabla1.setText("Visualizar tabla 2");
        jButtonTabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabla1ActionPerformed(evt);
            }
        });

        jTableVisualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVisualizar);

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabla2ActionPerformed
        float monto= Float.parseFloat(jTextFieldMonto.getText());
        ListaLEG<Mozo> listita= listM.mozosMontoSup(monto);
        NodoLEG<Mozo> ptr=listita.getPrimero();
        String []titulo={"Mozo","Año Expe","CantidadPlatos","MontoRecaudado"};
        modelo= new DefaultTableModel(null,titulo);

        if (listM.getPrimero().getDato().getPedidos().colaVacia()==true) {
            JOptionPane.showMessageDialog(null,"Debe registrar Pedidos");
        }else{
            if (listita.getPrimero()==null) {
                JOptionPane.showMessageDialog(null,"No hay ningun dato encontrado..");
            }else{
                Object [] cad;
                int sum;
                ArrayCola<Pedido> Caux= new ArrayCola<Pedido>();
                while(ptr!=null){
                    sum=0;
                    cad= new Object[4];
                    cad[0]=ptr.getDato().getApellidos();
                    cad[1]=ptr.getDato().getAñosExperiencia();
                    while(ptr.getDato().getPedidos().colaVacia()==false){
                        Pedido p= ptr.getDato().getPedidos().desencolar();
                        for (int i = 0; i < p.getnP(); i++) {
                            sum+=p.getPlatos()[i].getCant();
                        }
                        Caux.encolar(p);
                    }
                    while(Caux.colaVacia()==false){
                        ptr.getDato().getPedidos().encolar(Caux.desencolar());
                    }
                    cad[2]=sum;
                    ptr.getDato().calcularMontoxMozo();
                    cad[3]=ptr.getDato().getMontoRecaudacion();
                    modelo.addRow(cad);
                    ptr=ptr.getSiguiente();
                }
                jTableVisualizar.setModel(modelo);

            }
        }
        jTextFieldMonto.setText("");
    }//GEN-LAST:event_jButtonTabla2ActionPerformed

    private void jButtonTabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabla1ActionPerformed
        int año= Integer.parseInt(jTextFieldAño.getText());
        ListaLEG<Mozo> listita= listM.listaMenorExperiencia(año);
        NodoLEG<Mozo> ptr=listita.getPrimero();
        String []titulo={"Mozo","Año Expe","CantidadPlatos","MontoRecaudado"};
        modelo= new DefaultTableModel(null,titulo);
        if (listM.getPrimero().getDato().getPedidos().colaVacia()==true) {
            JOptionPane.showMessageDialog(null,"Debe registrar Pedidos");
        }else{
            if (listita.getPrimero()==null) {
                JOptionPane.showMessageDialog(null,"No hay ningun dato encontrado..");
            }else{
                Object [] cad;
                int sum;
                ArrayCola<Pedido> Caux= new ArrayCola<Pedido>();
                while(ptr!=null){
                    sum=0;
                    cad= new Object[4];
                    cad[0]=ptr.getDato().getApellidos();
                    cad[1]=ptr.getDato().getAñosExperiencia();
                    while(ptr.getDato().getPedidos().colaVacia()==false){
                        Pedido p= ptr.getDato().getPedidos().desencolar();
                        for (int i = 0; i < p.getnP(); i++) {
                            sum+=p.getPlatos()[i].getCant();
                        }
                        Caux.encolar(p);
                    }
                    while(Caux.colaVacia()==false){
                        ptr.getDato().getPedidos().encolar(Caux.desencolar());
                    }
                    cad[2]=sum;
                    ptr.getDato().calcularMontoxMozo();
                    cad[3]=ptr.getDato().getMontoRecaudacion();
                    modelo.addRow(cad);
                    ptr=ptr.getSiguiente();
                }
                jTableVisualizar.setModel(modelo);

            }
        }
        jTextFieldAño.setText("");
    }//GEN-LAST:event_jButtonTabla1ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        myHome v = new myHome();
        v.listM = listM;
        v.setVisible(true);

    }//GEN-LAST:event_jButtonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonTabla1;
    private javax.swing.JButton jButtonTabla2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVisualizar;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
